### ISSUE TITLE
Incompatibility to current mongo-ruby-driver 2.5.0

### ISSUE THREAD

**Issue by aboutNisblee** [reidmorrison/mongo_ha#2]
Hey @reidmorrison ,

thanks for your litte extension to mongo-ruby-driver. Unfortunately, it seems to be incompatible to the current v2.5.0 release. Maybe you missed the changes made by [RUBY-1229](https://jira.mongodb.org/browse/RUBY-1229)?

Best regards ...

**Comment by reidmorrison** [comment]
The latest gem is now compatible with v2.5.0
